id: P58C3319C
initial_creation_type: input
source_metadata:
  Title: Gilgit Manuscripts
  Editor: Dutt, Nalinaksa
  Publisher: Sri Satguru Publications
  Place of Publication: Delhi
  Year: '1984'
  Āryābuddhabalādhānaprātihāryavikurvaṇanirdeśanā mamahāyānasūtram:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:09:05.047234'
last_modified_at: '2022-03-08T16:09:05.047241'
